### ISSUE TITLE
Send-MQTTValue Problem "Cannot bind parameter 'SecureString' Cannot convert the "password" value of type "System.String" to type "System.Security.SecureString".

### ISSUE THREAD

**Issue by gnagflow80** [aaronsb/REC-BMSManager#5]
Hi Aaron,
a last thing a cant get to run is the Send-MQTTValue (by the way in your Readme it is only called Send-MQTT).
I installed the MQTT Server and Clilent. But, if i run your script i get following message and i cant get any values in MQTT explorer.

![grafik](https://user-images.githubusercontent.com/81044114/111903685-cbb4d580-8a43-11eb-86f0-6e7d9841defe.png)

This is my mqtt config file:
![grafik](https://user-images.githubusercontent.com/81044114/111903888-7cbb7000-8a44-11eb-8bf5-9b103d354f43.png)

 
The defined password and user are the same as i use when applying your send-MQTTValue script. Any idea?
thank you!

**Comment by gnagflow80** [comment]
changed from: $PWD  = ConvertFrom-SecureString -SecureString $Password -AsPlainText
to: $PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText

in: Send-MQTTValue.ps1

error message is gone, but still my mqtt server doesnt receive data..

**Comment by aaronsb** [comment]
There is a constructor (function) called use-bmsmqttconfiguration, the brokerpath is set from joined paths, that might be one thing.
![image](https://user-images.githubusercontent.com/2738471/111907996-84b7e780-8a25-11eb-8d34-947ca169b5c1.png)

If you instance the module as you normally would (so you could get a bms parameter for example)
What value is returned if you type "$BMSInstructionSet.Config.MQTT" at the powershell prompt?

**Comment by aaronsb** [comment]
Please remember that powershell returns objects, not strings. (even a string is actually an object). I would expect $BMSInstructionSet.Config.MQTT returns the object of type pscustomobject which was serialized from json, and includes the password text in it.

**Comment by aaronsb** [comment]
Isn't that the same command?

$PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText
$PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText

> changed from: $PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText
> to: $PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText
> 
> in: Send-MQTTValue.ps1
> 
> error message is gone, but still my mqtt server doesnt receive data from topics, but receives only $SYS data.

**Comment by gnagflow80** [comment]
> 
> 
> There is a constructor (function) called use-bmsmqttconfiguration, the brokerpath is set from joined paths, that might be one thing.
> ![image](https://user-images.githubusercontent.com/2738471/111907996-84b7e780-8a25-11eb-8d34-947ca169b5c1.png)
> 
> If you instance the module as you normally would (so you could get a bms parameter for example)
> What value is returned if you type "$BMSInstructionSet.Config.MQTT" at the powershell prompt?

![grafik](https://user-images.githubusercontent.com/81044114/111909753-d466d500-8a5e-11eb-97e1-64bffe1c389b.png)

**Comment by gnagflow80** [comment]
> 
> 
> Isn't that the same command?
> 
> $PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText
> $PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText
> 
> > changed from: $PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText
> > to: $PWD = ConvertFrom-SecureString -SecureString $Password -AsPlainText
> > in: Send-MQTTValue.ps1
> > error message is gone, but still my mqtt server doesnt receive data from topics, but receives only $SYS data.

sorry was a mistake:
![grafik](https://user-images.githubusercontent.com/81044114/111909821-0e37db80-8a5f-11eb-89c0-c531c85ccb16.png)

**Comment by gnagflow80** [comment]
> 
> 
> There is a constructor (function) called use-bmsmqttconfiguration, the brokerpath is set from joined paths, that might be one thing.
> ![image](https://user-images.githubusercontent.com/2738471/111907996-84b7e780-8a25-11eb-8d34-947ca169b5c1.png)
> 
> If you instance the module as you normally would (so you could get a bms parameter for example)
> What value is returned if you type "$BMSInstructionSet.Config.MQTT" at the powershell prompt?

The BrokerPath looks good, isn't it:
![grafik](https://user-images.githubusercontent.com/81044114/111910167-8f43a280-8a60-11eb-8b1b-fcbf6faf78b5.png)

**Comment by aaronsb** [comment]
maybe whats happening is you're not using the installer script? I updated some unfinished ends on it. Take a look at the relevant readme section here. (watch videos)

![image](https://user-images.githubusercontent.com/2738471/111911985-a8832980-8a35-11eb-86f4-cde1cb5c163f.png)

**Comment by aaronsb** [comment]
also I'd point out that once you have a service poller against the rec-bms, you need to be careful you're not issuing commands during the service poller. There's no lockout of resources (serial port, communication with bms hardware). 

_someday in the future_ I would like to change this to more of a typical service architecture, so the service module reads a command queue and returns the commands to the correct requester. This would eliminate device resource contention.

**Comment by gnagflow80** [comment]
> 
> 
> maybe whats happening is you're not using the installer script? I updated some unfinished ends on it. Take a look at the relevant readme section here. (watch videos)
> 
> ![image](https://user-images.githubusercontent.com/2738471/111911985-a8832980-8a35-11eb-86f4-cde1cb5c163f.png)

Thank you a lot. It is working now! I did not install the REC-BMSMaanger within the right path. I followed your updated description and putted the module now into this path as you described: /opt/microsoft/powershell/7/....

MANY THANKS.
Having the BMS Parameter within the MQTT opens up all kind of logging possibilities!!

**Comment by aaronsb** [comment]
Ok, closing this for now. Let me know what else happens, log bugs. You're officially the first person besides me to use this mqtt shipper. :)
